permissions:
  contents: read

jobs:
  changes:
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      charts: ${{ steps.filter.outputs.charts }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - id: filter
        uses: dorny/paths-filter@83deb9f0373c586f6db8c56afa94bc6e0e994432 # v2.2.0
        with:
          filters: |
            charts:
              - 'charts/**/Chart.yaml'
              - 'charts/**/*'
          token: ${{ secrets.GITHUB_TOKEN }}
  helm-lint-test:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm chart
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Fetch history
        run: git fetch --prune --unshallow
      - name: Set up chart-testing
        uses: helm/chart-testing-action@b0d4458c71155b54fcf33e11dd465dc923550009 # v2.0.1
      - name: Run chart-testing (lint)
        run: ct lint
      # Only build a kind cluster if there are chart changes to test.
      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
      - if: steps.list-changed.outputs.changed == 'true'
        name: Create kind cluster
        uses: helm/kind-action@7a937c0fb648064a83b8b9354151e5e543d9fcec # v1.1.0
      - if: steps.list-changed.outputs.changed == 'true'
        name: Run chart-testing (install)
        run: ct install
  helm-docs-validate:
    if: ${{ needs.changes.outputs.charts == 'true' }}
    name: Helm Docs
    needs:
      - changes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
      - name: Run helm-docs
        uses: docker://jnorwood/helm-docs:v1.3.0@sha256:12f065115654c9a1d6819b938487d327f1fdb5c32bdc2a5c74afef22ed68f5ca # jnorwood/helm-docs:v1.3.0
      - name: Check for changes
        run: git diff --quiet charts/*/README.md

name: Lint and Test Charts
on: pull_request
